ASoC: atmel: mchp-asrc: fix printk format specifier warnings
commit c2ea24dbb47ec01559eac23368bfa5324d637b08 from
https://github.com/linux4microchip/linux.git linux-6.6-mchp+fpga

This patch fixes the following warnings discovered on 64 bit platforms:

sound/soc/atmel/mchp-asrc.c:1275:25: error: format '%x' expects
argument of type 'unsigned int', but argument 6 has type 'dma_addr_t'
{aka 'long long unsigned int'} [-Werror=format=]

sound/soc/atmel/mchp-asrc-dma.c:275:17: error: format '%x' expects
argument of type 'unsigned int', but argument 6 has type 'phys_addr_t'
{aka 'long long unsigned int'} [-Werror=format=]

sound/soc/atmel/mchp-asrc-dma.c:677:25: error: format '%u' expects
argument of type 'unsigned int', but argument 6 has type 'size_t'
{aka 'long unsigned int'} [-Werror=format=]

Fix specifiers using guidance in [1].

Link: https://www.kernel.org/doc/Documentation/printk-formats.txt [1]
Fixes: 0b902c530936 ("ASoC: atmel: Add ASRC driver")
Signed-off-by: Cristian Birsan <cristian.birsan@microchip.com>
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Acked-by: Nicolas Ferre <nicolas.ferre@microchip.com>
(cherry picked from linux-6.1-trunk/at91/sound)
Signed-off-by: Andrei Simion <andrei.simion@microchip.com>
Signed-off-by: harish h <harish.h@windriver.com>