ASoC: atmel: fix a pair of Wtautological-overlap-compare
commit ee71faf358b53da07ab3bf01dc4b245605753793 from
https://github.com/linux4microchip/linux.git linux-6.6-mchp+fpga

Clang complains:
sound/soc/atmel/mchp-asrc-card.c:493:33: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
        if (priv->convert_channels < 1 && priv->convert_channels > 8) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/soc/atmel/mchp-asrc-card.c:478:32: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
        if (priv->convert_rate < 8000 && priv->convert_rate > 192000) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

It would appear that these were meant to be ensuring the value lies with
in the range, so swap them both to ||.

Reviewed-by: Claudiu Beznea <claudiu.beznea@microchip.com>
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
(cherry picked from linux-6.1-trunk/at91/sound)
Signed-off-by: Andrei Simion <andrei.simion@microchip.com>
Signed-off-by: harish h <harish.h@windriver.com>